# Generated by Django 3.2.6 on 2021-08-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('running_time', models.TimeField()),
                ('cast', models.ManyToManyField(to='people.Person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
